### ISSUE TITLE
undefined reference to symbol 'pthread_setname_np@@GLIBC_2.12'

### ISSUE THREAD

**Issue by koppi** [kronihias/mcfx#1]
On Ubuntu 16.04: I'm getting:

```
[ 36%] Linking CXX executable ../../_bin/standalone/mcfx_convolver_standalone36
/usr/bin/ld: ../../JUCE/libJUCE_STATIC.a(juce_core.cpp.o): undefined reference to symbol 'pthread_setname_np@@GLIBC_2.12'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
mcfx_convolver/mcfx_convolver_standalone/CMakeFiles/mcfx_convolver_standalone36.dir/build.make:237: recipe for target '_bin/standalone/mcfx_convolver_standalone36' failed
make[2]: *** [_bin/standalone/mcfx_convolver_standalone36] Error 1
```

Any hints?

**Comment by silvioprog** [comment]
Just add the option `-pthread` to your build suite, e.g: `set(CMAKE_C_FLAGS "-pthread")`.

**Comment by kronihias** [comment]
there was a problem with the wrong order of linking... fixed that in cmakelists

**Comment by ghost** [comment]
I had the same issue. Adding -pthread to CMAKE_CXX_FLAGS solved it. Could it be automated (in some cmake config)?

**Comment by kronihias** [comment]
@marclava, i just pushed a changed that should fix this and other problems with linux, let me know if there is any remaining problem. thanks!

**Comment by ghost** [comment]
It fixed problems with the plugins, but the controls of the standalones are not reacting to mouse clicks.

**Comment by kronihias** [comment]
strange, standalone gui works fine for me in ubuntu 18.04

**Comment by ghost** [comment]
I configured the mcfx_convolver project for JUCE 5.4.5 (and changed a few things in the source code so it compiles) and now the GUI is working in the app (but there's no jackd support). But I just need the VST version, so I won't suffer too much.
