### ISSUE TITLE
Delay plugins introduce discontinuities

### ISSUE THREAD

**Issue by mtmccrea** [kronihias/mcfx#2]
I have found that the mcfx_delayN plugins (v0.5.1 and v0.5.2) introduce discontinuities in the waveform. The problem is more audible with certain material, namely sinusoidal material, but can be inaudible with others.

The discontinuities come in "pairs" which are separated in time by multiples of the system's hardware buffer size. Sometimes the separation is equal to the hardware buffer size, sometimes it's less (e.g. half the buffer size). This leads me to believe that the read/write pointers are cycling through the delay buffer are not cycling correctly.

I've noticed that sometimes the problem looks like a repeated sample, though other times not, so this may be a coincidence. In any case the issue seems dependent on the material in the delay buffer. Notice in the screenshot below that the "impulses" created by the discontinuity are not always of the same strength within the "pair" and across channels.

<img width="1308" alt="screen shot 2017-04-24 at 1 33 41 pm" src="https://cloud.githubusercontent.com/assets/923342/25358106/2959941e-28f5-11e7-8f27-8421a8f9232a.png">

The issue is more obvious with a sine tone:

<img width="1312" alt="screen shot 2017-04-24 at 1 39 36 pm" src="https://cloud.githubusercontent.com/assets/923342/25358155/56557dd4-28f5-11e7-8eda-2299c9b54cbd.png">

An example discontinuity:
<img width="208" alt="screen shot 2017-04-24 at 1 31 16 pm" src="https://cloud.githubusercontent.com/assets/923342/25358177/691a7938-28f5-11e7-94ae-56be5b703ac7.png">

Showing the spacing of each impulse in a "pair" is a subdivision of the hw buffer size (power of 2):
<img width="746" alt="screen shot 2017-04-24 at 1 40 57 pm" src="https://cloud.githubusercontent.com/assets/923342/25358210/839238f0-28f5-11e7-8bc8-7967ccd50ee6.png">

I've tested this in both Reaper and Adobe Audition, so it appears not to be a problem with the host application.

Thanks for your work on this!

**Comment by kronihias** [comment]
Hi @mtmccrea,
thanks for the detailed bug report!
I fixed this with commit 0177a8ebb60dc3641826345d74019aefe262f605 and I will build a new release soon.
Best, Matthias

**Comment by mtmccrea** [comment]
Great, it's much appreciated! Thanks for your work on these plugins!
