### ISSUE TITLE
ubuntu build issue

### ISSUE THREAD

**Issue by pkviet** [kronihias/mcfx#3]
hello
it seems there is still a linking order problem with pthread  in spite of the commit in march.
I wasn't able to find the correct order.
os: ubuntu 17.04

~/mcfx/build$ make
[ 17%] Built target JUCE_STATIC
[ 25%] Built target mcfx_convolver36
[ 26%] Linking CXX executable ../../_bin/standalone/mcfx_convolver_standalone36
/usr/bin/ld: ../../JUCE/libJUCE_STATIC.a(juce_core.cpp.o): référence au symbole non défini «pthread_setname_np@@GLIBC_2.12»
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line

**Comment by guildfordia** [comment]
having the same problem here
ubuntu 18.04

saw that it was supposed to be fixed in a previous thread. but i don't totally get where to put `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")` in the CMakeLists.txt file

**Comment by kronihias** [comment]
should be fixed with commit 92ceeb3fdff6cd8ef5a64657c4059cd1bdd4d85b
